### ISSUE TITLE
Error on get dependency just with name

### ISSUE THREAD

**Issue by lucasdidur** [marcguilera/dart_dependencies#4]
```
InjectorManager.injectorBuilder.bindSingleton((i, p) => PaisLoader(), name: "PaisLoader");

InjectorManager.injector.bindings.forEach((f) => (print("name: " + f.name +" type: " + f.type.toString())));

print(InjectorManager.injector.get(name: "PaisLoader"));
```

```
name: PaisLoader type: (dynamic, dynamic) => PaisLoader
Unhandled exception:
InjectionException: Can't get unregistered key `type:Object_name:PaisLoader`
#0      _RegistrationContainer.get (package:dependencies/src/registration/_registration_container.dart:22:7)
#1      _InjectorContainer.getRegistration (package:dependencies/src/injector/_injector_container.dart:20:22)
#2      _InjectorBase.get (package:dependencies/src/injector/_injector_base.dart:10:12)
#3      main (package:produtor_common/arquitetura/proxy/proxy_manager.dart:40:34)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by Cilestal** [comment]
print(InjectorManager.injector.get<PaisLoader>(name: "PaisLoader"));
